services:
  api:
    build: ./api
    container_name: express_api
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"

  db:
    image: postgres:16
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: bruised_banana_admin
      POSTGRES_PASSWORD: supersecret06
      POSTGRES_DB: main_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db-schema.sql:/docker-entrypoint-initdb.d/db-schema.sql:ro

  frontend:
    build: ./frontend
    container_name: react_frontend
    env_file:
      - .env
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"

volumes:
  pgdata:
